name: typing_aware_field
description: A Flutter package that provides a TypingAwareTextFormField widget to detect user typing.
version: 1.0.0
homepage: https://github.com/itsAyyazdev/typing_aware_field
repository: https://github.com/itsAyyazdev/typing_aware_field.git
issue_tracker: https://github.com/itsAyyazdev/typing_aware_field/issues

environment:
  sdk: ^3.7.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter